# Generated by Django 4.2.3 on 2023-08-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feekback',
            new_name='Give_a_Valueable_feedback',
        ),
    ]
