# Generated by Django 4.2.3 on 2023-08-27 19:56

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_feekback_feedback_give_a_valueable_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=200, validators=[restaurant.models.characters_only]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=200, validators=[restaurant.models.characters_only]),
        ),
    ]
