# Generated by Django 4.2.3 on 2023-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_booking_comment_alter_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
